// <auto-generated />
using Engini.Employees.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Engini.Employees.Api.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20260301213042_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Engini.Employees.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice (CEO)"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 1,
                            Name = "Bob (Head of Engineering)"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 2,
                            Name = "Carol (Engineering Manager)"
                        },
                        new
                        {
                            Id = 4,
                            ManagerId = 3,
                            Name = "Dan (Team Lead)"
                        },
                        new
                        {
                            Id = 5,
                            ManagerId = 4,
                            Name = "Eva (Senior Developer)"
                        },
                        new
                        {
                            Id = 6,
                            ManagerId = 4,
                            Name = "Frank (Developer)"
                        },
                        new
                        {
                            Id = 7,
                            ManagerId = 3,
                            Name = "Grace (QA Engineer)"
                        },
                        new
                        {
                            Id = 8,
                            ManagerId = 1,
                            Name = "Henry (Head of HR)"
                        },
                        new
                        {
                            Id = 9,
                            ManagerId = 8,
                            Name = "Irene (Recruiter)"
                        });
                });

            modelBuilder.Entity("Engini.Employees.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Engini.Employees.Domain.Entities.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Engini.Employees.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
